### ISSUE TITLE
SshConnectionException: The server response contains a null character

### ISSUE THREAD

**Issue by daveMueller** [sshnet/SSH.NET#1176]
Hi guys,

so I have this device I want to send commands to via an ssh connection. When I connect with your library I get the already mentioned exception.

```batch
Exception occurred during SSH Client connect: Renci.SshNet.Common.SshConnectionException: The server response contains a null character at position 0x0000000C:

  00000000  FF FB 03 FF FC 01 FF FE 01 FF FE 00              ............

A server must not send a null character before the Protocol Version Exchange is complete.

More information is available here:
https://tools.ietf.org/html/rfc4253#section-4.2
   at Renci.SshNet.Connection.ProtocolVersionExchange.SocketReadLine(Socket socket, TimeSpan timeout, List`1 buffer)
   at Renci.SshNet.Connection.ProtocolVersionExchange.Start(String clientVersion, Socket socket, TimeSpan timeout)
   at Renci.SshNet.Session.Connect()
   at Renci.SshNet.BaseClient.CreateAndConnectSession()
   at Renci.SshNet.BaseClient.Connect()
```

I know that this device has the error because it seems to be sending a bad formatted version for the exchange. The version information is not like specified in [rfc4253](https://datatracker.ietf.org/doc/html/rfc4253). I've also seen the other issues #769 and #761 related to this and tried out the newest version, but I'm still getting this error.

But is there any workaround? 
Or do you have any option to make the protocol version exchange not so strict? 

I can properly send all the commands to this device via putty without noticing an error. It seems putty is a bit more resilient to bad formatted version.

**Comment by WojciechNagorski** [comment]
Can you download the project and comment these lines:
https://github.com/sshnet/SSH.NET/blob/dcc596a774182d0e5f605e90f4f8e9fe6e7f78db/src/Renci.SshNet/Connection/ProtocolVersionExchange.cs#L145-L149

It would be great to see if it works without this check.

**Comment by daveMueller** [comment]
Thanks @WojciechNagorski 🙏, I will try it and get back here once I have some feedback.

**Comment by daveMueller** [comment]
Unfortunately we are getting the next exception now:

```batch
Renci.SshNet.Common.SshOperationTimeoutException: Socket read operation has timed out after 30000 milliseconds.
   at Renci.SshNet.Abstractions.SocketAbstraction.Read(Socket socket, Byte[] buffer, Int32 offset, Int32 size, TimeSpan readTimeout)
   at Renci.SshNet.Connection.ProtocolVersionExchange.SocketReadLine(Socket socket, TimeSpan timeout, List`1 buffer)
   at Renci.SshNet.Connection.ProtocolVersionExchange.Start(String clientVersion, Socket socket, TimeSpan timeout)
   at Renci.SshNet.Session.Connect()
   at Renci.SshNet.BaseClient.CreateAndConnectSession()
   at Renci.SshNet.BaseClient.Connect()
```

**Comment by WojciechNagorski** [comment]
Maybe this is related to this issue: https://github.com/sshnet/SSH.NET/pull/841/files

I have a big request to check. I don't have this kind of device.

**Comment by daveMueller** [comment]
Sure thanks. We successfully use SSH.NET for a couple of other devices, really annoying that it doesn't work for this one. Maybe we also try the PR you linked next week. Thanks a lot for your support @WojciechNagorski 🙏 .

**Comment by repettigiorgio** [comment]
Good evening,
I already have this problem

Renci.SshNet.Common.SshConnectionException: The server response contains a null character at position 0x0000000B:
  00000000  53 53 48 2D 32 2E 30 2D 0D 0A 00                 SSH-2.0-...
A server must not send a null character before the Protocol Version Exchange is complete.

Is there an expected fix? or a workaround?

Thanks in advance

**Comment by Rob-Hague** [comment]
@repettigiorgio this was fixed in 2024.2.0

**Comment by john1726** [comment]
At this time I am using 2025.0.0 but am still receiving this error.  I suspect that the error may be related to [Polly](https://martintmk.github.io/Polly/) v8.6.4.
```
Renci.SshNet.Common.SshConnectionException: The server response contains a null character at position 0x00000001:
  00000000  00                                               .
A server must not send a null character before the Protocol Version Exchange is complete.
More information is available here:
https://tools.ietf.org/html/rfc4253#section-4.2
   at Renci.SshNet.Connection.ProtocolVersionExchange.CreateServerResponseContainsNullCharacterException(List`1 buffer)
   at Renci.SshNet.Connection.ProtocolVersionExchange.SocketReadLineAsync(Socket socket, List`1 buffer, CancellationToken cancellationToken)
   at Renci.SshNet.Connection.ProtocolVersionExchange.StartAsync(String clientVersion, Socket socket, CancellationToken cancellationToken)
   at Renci.SshNet.Session.ConnectAsync(CancellationToken cancellationToken)
   at Renci.SshNet.BaseClient.CreateAndConnectSessionAsync(CancellationToken cancellationToken)
   at Renci.SshNet.BaseClient.ConnectAsync(CancellationToken cancellationToken)
   at Polly.AsyncPolicy.<>c__DisplayClass44_0.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
```

**Comment by Rob-Hague** [comment]
@john1726 your issue is different - the server appears to be sending a null (zero) byte without any identification part. Are you connecting to the right port? Does any other client work?

**Comment by john1726** [comment]
> [@john1726](https://github.com/john1726) your issue is different - the server appears to be sending a null (zero) byte without any identification part. Are you connecting to the right port? Does any other client work?

It is an Azure Function App and a storage account with SFTP enabled.  Determined that the issue was that I had a json config set for HTTP but it should have been SFTP.
