### ISSUE TITLE
Connections are staying open

### ISSUE THREAD

**Issue by PatrickSchmidtSE** [sshnet/SSH.NET#169]
I have a problem with connections that are staying open. I use the Lib to connect to an Sophos UTM via SSH and in the connection logs you see many open ssh connections when i use the LIB (i connect, do several stuff and then disconnect, and this is an interval).

ISRZ-MCS:/root # last | grep "still logged in" 
loginuse pts/21       172.16.75.1      Fri Feb 10 10:58   still logged in    
loginuse pts/20       172.16.75.1      Fri Feb 10 10:45   still logged in    
loginuse pts/19       172.16.75.1      Fri Feb 10 10:31   still logged in    
loginuse pts/17       172.16.75.1      Fri Feb 10 10:28   still logged in    root     
pts/18       port-92-198-130- Fri Feb 10 10:10   still logged in    

After a short call with the Sophos UTM team, they said, that every time i connect with the lib several Confd-client processes are appearing. 

`client = new SshClient(conInfo);
 client.KeepAliveInterval = new TimeSpan(0, 0, 0, 10, 0);
 this.client.ErrorOccurred += client_ErrorOccurred;
 client.Connect();

if (client != null) {
     client.Disconnect();
     client = null;
 }
#dostuff

`

Is anything like that known or already fixed ( I currently still use version 2014.4.6.0 because of .NET 3.5)? 
I just want to make sure that something like this is fixed in newer releases or can be fixed till we upgrade to a newer .NET version.

Thank you in advance. If any further information is required just ask.

**Comment by drieseng** [comment]
Quite some issue have been fixed since that release, but I don't recall a similar issue.
I'll try to release a new beta *soonish*. That one should work just fine on .NET 3.5.
If you can build from the **develop** branch, you can already verify whether it fixes this problem.

**Comment by PatrickSchmidtSE** [comment]
Thanks i will try it out then :)

**Comment by drieseng** [comment]
Please provide feedback as soon as you had time to try it out.

**Comment by PatrickSchmidtSE** [comment]
I wanted to test it but with the same code, the new version is not able to connect at all to the sophos UTM.

System.ArgumentNullException: Der Wert darf nicht NULL sein.
Parametername: Alle Listen sind NULL oder leer.
   bei Renci.SshNet.Session.WaitOnHandle(WaitHandle waitHandle, TimeSpan timeout)
   bei Renci.SshNet.Session.Connect()
   bei Renci.SshNet.BaseClient.Connect()
   bei Agents.Helpers.SSH.SSH.connect() in \SSH.cs:

"All lists are null or empty" i would translate the message like that. Its weird.. I need to check first if there are other changes necessary..

**Comment by PatrickSchmidtSE** [comment]
I have the same error as on this 

https://github.com/sshnet/SSH.NET/issues/113

**Comment by drieseng** [comment]
That issue is fixed in the **develop** branch.
Would it possible for you to build **SSH.NET** from source?
I'm waiting for feedback on issue #175 to release a new beta.

**Comment by PatrickSchmidtSE** [comment]
Sure i will. But i am not sure how fast i can test again this build. The Sophos is not in my direct access. But i guess the problem still can lie somewhere else, as the logs of confd are clean for a few days now and if this stays i guess this can be closed.

I will report on you on thursday or friday. If the problem did not occur again, we can close this otherwise i will make a test asap against the develop branch.

**Comment by PatrickSchmidtSE** [comment]
It was just a problem with the frequency of the ssh connections. Sorry for the issue and thank you for your fast answers.
