### ISSUE TITLE
Add interface to SftpClient.

### ISSUE THREAD

**Issue by ericbrumfield** [sshnet/SSH.NET#193]
This would be handy to have for testing and mocking and I'd like to contribute to this feature if possible.

**Comment by CasperWSchmidt** [comment]
This really should be merged! Along with ISftpFile interface for SftpFile :)

In my project I have implemented wrappers with interfaces IFtpFileWrapper and IFtpClientWrapper to be able to separate SSH.Net from most of my classes and enable unit testing. But it is not very pretty :(

**Comment by benjaminoerskov** [comment]
Im still having a hard time mocking some of the methods in the SftpClient. 
I came across the method Connect() which does not exist in the Interface, but comes from the BaseClient.
Would it be possible to add such methods to the ISftpClient interface? Or how would you mock them?

**Comment by CasperWSchmidt** [comment]
@benjaminoerskov I would say that Connect is a pretty important part of the abstraction. An interface for communicating with a FTP server is not of much use if you can't connect to it 😊
Therefore I will argue that it obviously should be part of the interface

**Comment by polly-utopi** [comment]
Are there any plans to add the Connect method to the interface?

**Comment by lugospod** [comment]
> @benjaminoerskov I would say that Connect is a pretty important part of the abstraction. An interface for communicating with a FTP server is not of much use if you can't connect to it 😊 Therefore I will argue that it obviously should be part of the interface

Yeap...connect should definitely be in the interface.

**Comment by sga-solita** [comment]
> Im still having a hard time mocking some of the methods in the SftpClient. I came across the method Connect() which does not exist in the Interface, but comes from the BaseClient. Would it be possible to add such methods to the ISftpClient interface? Or how would you mock them?

I found this answer, because I'm sitting in the same situation. To be able to use SftpClient with Dependency Injection, I need to Connect when I inject the client into my dependent classes, which feels wrong. If something goes wrong with Connect, it shouldn't be thrown from the injecting part, but instead inside the dependent class. At least in my case.

**Comment by CasperWSchmidt** [comment]
All of this should be fixed in #975 but we're still waiting for it to be released

**Comment by berv63** [comment]
Can we get a readme update with some use cases on how to connect using the interface?

**Comment by CasperWSchmidt** [comment]
@berv63 it's impossible as it is now, but exactly the same as using the class directly when this PR gets released

**Comment by zhilbug** [comment]
Is this going to be released?
