### ISSUE TITLE
Server identification problem in NETStandart 2.0

### ISSUE THREAD

**Issue by Kutikov** [sshnet/SSH.NET#377]
`Renci.SshNet.Common.SshConnectionException: "Server response does not contain SSH protocol identification."`  - VS 2017, causes only using UWP with NETStandart 2.0, but on UWP with NETCore there were no problems. After 2,5 hours of testing I`ve found out that problem is in timeouts of Session/ Could you fix it up?

**Comment by drieseng** [comment]
Can you provide more information? Do you have a small application (source) that allows me to reproduce this issue?

What version of **SSH.NET** are you using?

**Comment by Kutikov** [comment]
I've got small server and I'm trying to access using code:
`SshClient sshClient = new SshClient(host, account, password);
sshClient.Connect():`
While minTarget version was 10.240, all works like a charm, but for using dotnetzip library I've changed minTarget version to FallCreatorsUpdate. As a result your library switchs from UAP10 version to NET 4.6.1 version and begins to reproduce this error. I haven't managed to debug your code, but I've found, that in Connect method in Session.cs there is some lines, that checks Ssh version after timeout. Maybe probleme placed there. You can reproduce that buf itself, using that code below and switching minTarget platform in UWP C# application in VS2017. It's important not to catch  `Renci.SshNet.Common.SshConnectionException` and try to connect.

I use 2016.1.0 version.

**Comment by drieseng** [comment]
Why do you mention .NET Standard 2.0 in the issue? We do not yet ship a .NET Standard 2.0 version.
Did you mean .NET Standard 1.3?

**Comment by theescapers** [comment]
I am experiencing this issue too, I'm using 2016.1.0 from NuGet, and building a UWP app against Fall Creators Update. I get failed SFTP connections on both my Linux server and Mac server. Both work fine with my other SFTP clients.

Version 2013.4.7 from NuGet doesn't have the problem, but I don't really want to drop back to such and old version.

**Comment by Kutikov** [comment]
Sorry, maybe I made a mistake and an issue caused by .NET Standart 1.3. Could you reproduce this issue?

**Comment by Kutikov** [comment]
For me version 2013.4.7 produced `Renci.SshNet.Common.SshConnectionException: "An established connection was aborted by the software in your host machine."`
Is there any way to make UAP only library to fix isssue NU1701 `Package 'SSH.NET 2016.1.0' was restored using '.NETFramework,Version=v4.6.1' instead the project target framework '.NETCoreApp,Version=v2.0'. This may cause compatibility problems. `

**Comment by drieseng** [comment]
@Kutikov Won't have time today. I'll try to test it tomorrow.

**Comment by Kutikov** [comment]
So is it any progress? If you don`t find out issue now, could you please build **separated .NETCore SSH.NET** for us to using it, while this issue would be fixed?

**Comment by drieseng** [comment]
Sorry too busy at work. Hope to have time this weekend.

**Comment by ghost** [comment]
I have encontered the same issue when connect sshclient, it throwing the exception:
 `Server response does not contain SSH protocol identification`
my environment is:
 Windows10 Fall Creators Update (Build 16299) SDK
 VS2017
SSH.NET v2016.1.0
So what I found the problems is: 
In Fall Creators Update and VS2017, the new UWP project will use .NETCore 2.0, which not be supported in current version.
You can try:
Downgrade the `Microsoft.NETCore.UniversalWindowsPlatform` in nugget package control panel from 6.x to 5.x. Which will use .NETCore 1.7 or eariler.
@theescapers

**Comment by stuwilliams-clgx** [comment]
"Server response does not contain SSH protocol identification"

Connecting from: 
* Server 2012 
* .NET CLR 4.6.1 

I connect to my linux s/FTP servers fine but when attempting to connect to: 
* Server 2008r2
* Windows s/FTP server

I am using simple username + password authentication.

Is there some setting or code snippet that I can use to force compatibility? 

I found the message in source in session.cs [612], is there a possible variation in the RegEx that should be considered?

**Comment by darkoperator** [comment]
Are you sure the 2008R2 is SSH/SFTP? The built in FTP server is FTP/FTPS(over SSL) and that is a nother protocol not SSH based

**Comment by KWinston** [comment]
@lyzl Was looking for a fix for a while and downgrading worked great to get it working on Build 16299, thanks!

**Comment by drieseng** [comment]
@Kutikov @theescapers @lyzl Can any of you still consistently reproduce this issue?

**Comment by Kutikov** [comment]
@drieseng, at this moment I can't check up functionality due to not using UWP and .NET Standart 1.3

**Comment by doodz** [comment]
hello,
@drieseng , I reproduce.
UWP project with XAMARIN.FORMS
WINDOWS 10,Version 1803 (10.0 ; Build 17134)
.NET Standard 2.0 , 
NuGet SSH.NET v2016.1.0

**Comment by rducom** [comment]
I reproduce on 10% of our integration builds. Not consistently
NetCore 2.1 on win10 & server2016
Last ssh.net nuget version + Syncplify server

**Comment by tipa** [comment]
Experiencing the same issue in my UWP app. It works when I have set build 10240/14393/15063 as min target version and it stops working as soon as I set the min target version to build 16299/17134.

**Comment by mbuchok** [comment]
Also receiving this error in .NET Core 2.1 on CentOS. Doesn't happen on all sftp connections... just one that I know of so far. Will see if I can gather some useful details later.

**Comment by nick-goloborodko** [comment]
Experiencing this issue too in UWP app on Windows IoT Core on raspberry pi 3 model b - and unfortunately, it is occurs in the critical function of the project

**Comment by doodz** [comment]
while waiting for a solution I use:
https://github.com/asmodat/Asmodat-Standard-SSH.NET
He corrected the problem.

**Comment by darkoperator** [comment]
one single huge commit :\ wish it was better documented as to what the changes are

**Comment by doodz** [comment]
For me, this is not the best alternative in the long run.
As I said, waiting for the correction, it could help @ nick-goloborodko in the medium term.

**Comment by avboivin** [comment]
@drieseng I sent you an email with my contact informations. I will be able to show you my configuration which is having this issue.

**Comment by avboivin** [comment]
After validating, it seems this issue is caused by the SFTP server actively refusing the connection using either a firewall rule or some sort of IP-based blocking.

This is not an issue caused by SSH.NET but rather by the connectivity to your SFTP server.

**Comment by drieseng** [comment]
@doodz @Kutikov @theescapers Can any of you consistently reproduce this issue, and provide me access to one of the (test) servers that show this issue?

**Comment by doodz** [comment]
hello @drieseng sorry for the late.
What you want say for server?
I'm use a vm in local and use my personal computer for start ssh session with ssh.net.
You want an access of my vm in ssh ?

**Comment by lprofitt** [comment]
I am having this problem with Iot Core, but only when using the loop back address in my UWP app. I use the loop back to run system commands outside of the app sandbox.

NOTE: I've not done a complete code analysis, this is just what I came up with after stepping through the code a few times.

I believe that it has something to do with the loop back connection being much faster than than the remote connection, but I'm not certain.

E.g. If I step through the code, and get the point that is highlighted in the below image, I get an unhanded `object disposed : Safe handle has been closed` exception.

![image](https://user-images.githubusercontent.com/43502682/50999987-c53c8200-14f9-11e9-9d14-033f5bd793b2.png)

I'm not sure why it only does it when I step through the code, but I suspect that, since the `SendCompleted `callback is called by each async call to `Send`, the threads are stomping on each other, since there is no lock mechanism, hence the "object disposed exception."

![image](https://user-images.githubusercontent.com/43502682/51000456-2d3f9800-14fb-11e9-9ce1-da34458fe0f7.png)

Anyway, I notice that the cause of the error is that when verifying the server version, there are no bytes returned. However, if you modify the` SocketAbstraction.Read `method as such:

![image](https://user-images.githubusercontent.com/43502682/51000713-e1412300-14fb-11e9-8c5d-81a1b0d992a5.png)

It returns the correct number of bytes read. 

You would also need to modify all other instances of the "sendReceiveToken.TotalBytesTransferred" for determining the number of bytes read.

However, rather than modifying the code, which seems risky to me since I don't know what kind of regression that might cause, I chose to define the `FEATURE_SOCKET_SYNC` compiler define at the top of the SocketAbstraction.cs file. This made it work for me. 

In my calling code I run a SSH command like this with a timeout:

![image](https://user-images.githubusercontent.com/43502682/51002021-fd46c380-14ff-11e9-992c-fe7b0ca787fc.png)

**Comment by erik-wramner** [comment]
We are also seeing this with .NET Core 2.2 and C# in Azure. It is fairly consistent; it happens with some servers and not with others. Unfortunately only in production, so I can't provide a test server. I will be happy to help testing a fix though.

@lprofitt did you create a fork? Ideally I'd like to change the calling code that I control rather than code in the library itself unless the official library can be fixed.

**Comment by lprofitt** [comment]
@erik-wramner, I did not create a fork, I just modified my local copy.

**Comment by M1XGear** [comment]
Any updates on solving this?

**Comment by Ashetyn** [comment]
I'm receiving this issue as well. any updates/ quick fixes?

**Comment by lprofitt** [comment]
@M1XGear  and @Ashetyn,
Pull the whole project down, and define the FEATURE_SOCKET_SYNC compiler define at the top of the SocketAbstraction.cs file and, it to your solution, and reference that rather than using nuget.

**Comment by EddyRts** [comment]
I'm also seeing this Exception a few times a day in our production environment: 
Renci.SshNet.Common.SshConnectionException: **Server response does not contain SSH protocol identification**.
   at Renci.SshNet.Session.Connect()
   at Renci.SshNet.BaseClient.Connect()

SSH.NET version: NuGet 2016.1.0.0
.NET version: .NET framework 4.7.2
Environment: Windows Server 2019
Language: C#

**Comment by natalie-o-perret** [comment]
Also experiencing that issue on our side

**Comment by KhalilMohammad** [comment]
Working fine locally in windows 10 but throwing exception in azure function app.

**Comment by zerathun** [comment]
I had the same issues. I started to try using other solutions on NUGET. Actually a Fork from Renci/SSH.NET solved this problem if anyone still is having issues.
https://www.nuget.org/packages/SSH.NET.Fork/2018.8.25.2?_src=template
With that Package my SSH Connection works just fine with UWP/Xamarin etc..

**Comment by drieseng** [comment]
I've identified a bug in our EAP socket implementation that surfaces when an async operation completes synchronously.

**Comment by karthik-v-raman** [comment]
I am getting ""Server response does not contain SSH protocol identification" consistently.
UWP project 
WINDOWS 10,Version 1803 (10.0 ; Build 17134)
.NET Standard 2.0 ,
NuGet SSH.NET v2016.1.0

I am trying to ssh to a hardware in my LAN. Putty ssh works.
Is there any update fix?

**Comment by dudi-dev** [comment]
I have the same issue using SSH.NET within my Azure Function deployed to Microsoft Azure. I use this library to check each minute for new files to download them and move them to another folder (just small text files). 

It works for about 1-3 days and then it stops working until I stop and start the Function again.

I'm using SSH.NET version 2016.1.0 in my .NET Core 3.1 project.

Maybe this information helps resolving the issue.

"Just my code" stack trace:
`Microsoft.Azure.WebJobs.Host.FunctionInvocationException:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithLoggingAsync>d__19.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.16.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.Azure.WebJobs.Host, Version=3.0.16.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.csMicrosoft.Azure.WebJobs.Host, Version=3.0.16.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: 322)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<TryExecuteAsyncCore>d__16.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.16.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.Azure.WebJobs.Host, Version=3.0.16.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.csMicrosoft.Azure.WebJobs.Host, Version=3.0.16.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: 117)
Inner exception Renci.SshNet.Common.SshConnectionException handled at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw:
   at Renci.SshNet.Session.Connect (Renci.SshNet, Version=2016.1.0.0, Culture=neutral, PublicKeyToken=1cee9f8bde3db106)
   at Renci.SshNet.BaseClient.Connect (Renci.SshNet, Version=2016.1.0.0, Culture=neutral, PublicKeyToken=1cee9f8bde3db106)
   at MyNamespace.MyClass.Receive (MyNamespace, Version=1.0.0.0, Culture=neutral, PublicKeyToken=nullMyNamespace, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: C:\MySourcecontrol\Functions\MyNamespace\MyClass.csMyNamespace, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: 40)
   at MyNamespace.MyClass.Run (MyNamespace, Version=1.0.0.0, Culture=neutral, PublicKeyToken=nullMyNamespace, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: C:\MySourcecontrol\Functions\MyNamespace\MyClass.csMyNamespace, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: 29)
   at lambda_method (Anonymously Hosted DynamicMethods Assembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null)
   at Microsoft.Azure.WebJobs.Host.Executors.VoidMethodInvoker`2.InvokeAsync (Microsoft.Azure.WebJobs.Host, Version=3.0.16.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.Azure.WebJobs.Host, Version=3.0.16.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidMethodInvoker.csMicrosoft.Azure.WebJobs.Host, Version=3.0.16.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: 20)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2+<InvokeAsync>d__10.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.16.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.Azure.WebJobs.Host, Version=3.0.16.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.csMicrosoft.Azure.WebJobs.Host, Version=3.0.16.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: 52)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<InvokeAsync>d__27.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.16.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.Azure.WebJobs.Host, Version=3.0.16.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.csMicrosoft.Azure.WebJobs.Host, Version=3.0.16.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: 585)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithWatchersAsync>d__26.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.16.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.Azure.WebJobs.Host, Version=3.0.16.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.csMicrosoft.Azure.WebJobs.Host, Version=3.0.16.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: 532)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithLoggingAsync>d__25.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.16.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.Azure.WebJobs.Host, Version=3.0.16.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.csMicrosoft.Azure.WebJobs.Host, Version=3.0.16.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: 468)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithLoggingAsync>d__19.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.16.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.Azure.WebJobs.Host, Version=3.0.16.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.csMicrosoft.Azure.WebJobs.Host, Version=3.0.16.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: 278)
`

**Comment by drieseng** [comment]
Fixed in https://github.com/sshnet/SSH.NET/commit/916c01926688c16d0e9058197741a1f342010ff4.

**Comment by fnicollier** [comment]
I've tried a build using the source code from May 3rd 2020 which has this fix but I still get the same issue when running on Azure Function: works fine for a day and then "Server response does not contain SSH".

Using .NET Core 3.1 on Azure Function v3.

**Comment by drieseng** [comment]
@fnicollier Can you reproduce this issue outside of Azure? Do you have a server I can test against?

If not, can you try moving [this](https://github.com/sshnet/SSH.NET/blob/e44913029e341329f8b8e3612025146927b4f28f/src/Renci.SshNet/Session.cs#L642) line to [here](https://github.com/sshnet/SSH.NET/blob/e44913029e341329f8b8e3612025146927b4f28f/src/Renci.SshNet/Session.cs#L608)

**Comment by fnicollier** [comment]
Sadly I can't reproduce this outside of Azure. I'm trying the change you suggest and will report back after we've done testing.

Update 1: Ran some tests and as before it first seems to run fine but eventually returns an error. But this time I'm getting the following error "An existing connection was forcibly closed by the remote host" which points to a server issue which would be an improvement.

**Comment by drieseng** [comment]
@fnicollier Thanks for the feedback

**Comment by drieseng** [comment]
[2020.0.0-beta1](https://github.com/sshnet/SSH.NET/releases/tag/2020.0.0-beta1) is now available, and includes this fix.

**Comment by fnicollier** [comment]
Thanks for maintaining this library!

**Comment by drieseng** [comment]
... and thanks for appreciating it :p

**Comment by EddyRts** [comment]
Since we had this issue with version 2016.1.0.0, I retried with the 2020.0.0-beta1 release but the problem still persist.

_Renci.SshNet.Common.SshConnectionException: Server response does not contain SSH protocol identification._

SSH.NET version: NuGet 2020.0.0-beta1
.NET version: .NET framework 4.7.2
Environment: Windows Server 2019

**Comment by asheroto** [comment]
I just updated Windows on my computer and am getting this now.  None of my code has changed.

**Comment by mayo589** [comment]
I have also this problem like @EddyRts. Hopefully updated my version to 2020.0.0-beta1 but still getting this error:

Server response does not contain SSH protocol identification

I am also on Win Server 2019 + .NET framework 4.7.2

**Comment by drieseng** [comment]
Can one of you provide (private) access to a non-production server that allows me to reproduce this issue?
